### ISSUE TITLE
로그인 체크하는 시점 수정 필요

### ISSUE THREAD

**Issue by zych1751** [webdonalds/YAS-frontend#27]
/add, /my-page로 주소창에 입력해서 들어가면, 로그인 체크하는 비동기작업이 끝나기 전에 각 컴포넌트에서 로그인 되어있지 않다고 판단해서 Redirect시키는 버그 수정 필요.

**Comment by hywook4** [comment]
이거 생각보다 심한듯 ㅋㅋㅋ 조금 우선순위를 높혀보는것도 좋을 것같음
