### ISSUE TITLE
로그인 유지가 안됨

### ISSUE THREAD

**Issue by zych1751** [webdonalds/YAS-frontend#48]

**Comment by hywook4** [comment]
원인을 찾았습니다. 
router.get('/access-token', async (request: express.Request, response: express.Response) => {
    const encryptedRefreshToken: string = (request.headers['x-access-token'] || request.query.token) as string;

header에도 일단 만료된 access token이 같이 딸려가서 발생하는문제.

**Comment by hywook4** [comment]
아 예전 브랜치에서 해서 그랬군요. 고쳐진거 확인됐습니당
